name: rebuilder_docs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  flutter_native_splash: ^2.3.10
  uuid: ^4.4.2
  flex_color_scheme: ^7.3.1
  path_provider: ^2.1.2
  colornames: ^0.1.0
  hive_flutter: ^1.1.0
  flutter_markdown: ^0.7.1
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  signals_flutter: ^5.2.2
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_native_splash:
  image: "assets/app_icon.png"
  color: "#000000"
  background_image: "assets/app_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
# dart run flutter_native_splash:create
# dart run flutter_launcher_icons